---
title: "Client Report - Whats in a name?"
subtitle: "Course DS 250"
author: "Logan Clark"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

The use of bible names like Peter, Mary, and Matha have all seen a decrease in usage. On the other hand names like Dominica and Logan have a seen a dramatic increase in usage. If you were born before 1980 you would be named from the bible. If you were born after 1980 you would be named from a more modern book or movie.

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

<!-- __Highlight the Questions and Tasks__ -->

## Birth Name

How does your name at your birth year compare to its use historically?

For my name and it's use historically it is in the middle of it's popularity. From 2000 and on you can see a huge increase in use of the name of Logan.

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
fig = px.line(df.query('name == "Logan"'),
  x="year", 
  y="Total", 
  color='name', 
  title='The Name Logan Used Per Year')

fig.add_shape(
    dict(
        type='line',
        x0=2000,
        x1=2000,
        y0=0,
        y1=10000,
        line=dict(color='red', dash='dash'),
    )
)

fig.add_annotation(
    x=2000,
    y=10000,
    text='Birth Year',
    showarrow=True,
    arrowhead=1,
)

fig.show()
```


## Age of Brittany

If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?

I would guess the age of 34 years old. The ages that I would not guess are between 44 years old and older as well as 23 years old and younger.

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here
fig = px.line(df.query('name == "Brittany"'),
  x="year", 
  y="Total", 
  color='name', 
  title='The Name Brittany Used Per Year')

fig.add_shape(
    dict(
        type='line',
        x0=1990,
        x1=1990,
        y0=0,
        y1=40000,
        line=dict(color='red', dash='dash'),
    )
)

fig.add_annotation(
    x=1990,
    y=40000,
    text='34 Years Old',
    showarrow=True,
    arrowhead=4,

)

fig.show()

```


## Bible Names

Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?

I noticed that all the names were popular during 1940 and 1960 but they became less popular after 1980.

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here

fig = px.line(df.query('name == ["Paul","Mary","Martha","Peter"] and year > 1920 and year < 2000'),
  x="year", 
  y="Total", 
  color='name', 
  title='Names Used Per Year')

fig.add_shape(
    dict(
        type='line',
        x0=1950,
        x1=1950,
        y0=0,
        y1=max(df['Total']),
        line=dict(color='pink', dash='dash'),
    )
)

fig.add_annotation(
    x=1950,
    y=54000,
    text='Mary',
    showarrow=True,
    arrowhead=4,

)

fig.add_annotation(
    x=1950,
    y=22000,
    text='Paul',
    showarrow=True,
    arrowhead=4,

)

fig.add_annotation(
    x=1940,
    y=9000,
    text='Martha',
    showarrow=True,
    arrowhead=4,

)

fig.add_annotation(
    x=1930,
    y=3300,
    text='Peter',
    showarrow=True,
    arrowhead=4,
    ax=0,
    ay=-40

)

fig.show()
```


## Popular Movie Name

Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?

The release of the first fast and furious was in 2001 and for the next couple of years there was a huge jump in the use of the name Dominic. After the sixth movie there was a decline in the name Dominic.

```{python}
#| label: Q4
#| code-summary: Read and format data
# Include and execute your code here

fig = px.line(df.query('name == "Dominic" and year > 1980'),
  x="year", 
  y="Total", 
  color='name', 
  title='The Name Dominic Used Per Year')

fig.add_trace(go.Scatter(
    x=[2001, 2003, 2013],
    y=[3387, 5216, 6306],
    mode="markers",
    name="Release Dates",
    textposition="top center"
))

fig.add_annotation(
    x=2001,
    y=3387,
    text='Fast and Furious (2001)',
    showarrow=True,
    arrowhead=4,
    ax=40,
    ay=55
)

fig.add_annotation(
    x=2013,
    y=6306,
    text='Fast 6 (2013)',
    showarrow=True,
    arrowhead=4,
)

fig.add_annotation(
    x=2003,
    y=5216,
    text='2 Fast 2 Furious (2003)',
    showarrow=True,
    arrowhead=4,
)

fig.show()
```
